### ISSUE TITLE
Compilation Error OpenCV Make

### ISSUE THREAD

**Issue by sharathchandra92** [sergeytulyakov/FaceCept3D#3]
Hi, 

I get the following error when when I try to build. I am using Ubuntu 14.04.

`Scanning dependencies of target HeadPoseEstimationFramework
[  2%] Building CXX object HeadPoseEstimationFramework/CMakeFiles/HeadPoseEstimationFramework.dir/Grabber/PCDGrabber.cpp.o
[  5%] Building CXX object HeadPoseEstimationFramework/CMakeFiles/HeadPoseEstimationFramework.dir/Grabber/OpenNIGrabber.cpp.o
[  8%] Building CXX object HeadPoseEstimationFramework/CMakeFiles/HeadPoseEstimationFramework.dir/Grabber/ProviderGrabber.cpp.o
[ 11%] Building CXX object HeadPoseEstimationFramework/CMakeFiles/HeadPoseEstimationFramework.dir/Grabber/GrabberBase.cpp.o
[ 14%] Building CXX object HeadPoseEstimationFramework/CMakeFiles/HeadPoseEstimationFramework.dir/Converter/KinectDataConverter.cpp.o
[ 17%] Building CXX object HeadPoseEstimationFramework/CMakeFiles/HeadPoseEstimationFramework.dir/Features/Calculator/CylinderOptimizedFeatureCalculator.cpp.o
[ 20%] Building CXX object HeadPoseEstimationFramework/CMakeFiles/HeadPoseEstimationFramework.dir/Features/Sampler/CylinderSampler.cpp.o
/home/psllsi/FaceCept3D/FaceCept3D/HeadPoseEstimationFramework/Features/Sampler/CylinderSampler.cpp:3:30: fatal error: opencv2\opencv.hpp: No such file or directory
 #include <opencv2\opencv.hpp>
                              ^
compilation terminated.`

Could you please let me know what's the issue? 

When I try to open pcl_openni_viewer, it throws a 'No Device Connected' error. Does this have anything to do with OpenNI1 vs OpenNI2 compatibility issue?

Thanks.

**Comment by sergeytulyakov** [comment]
Hi,

Your compiler is not able to find <opencv2\opencv.hpp>. 
Did you install opencv?

**Comment by duchengyao** [comment]
@sergeytulyakov  <opencv2\opencv.hpp>  should be <opencv2/opencv.hpp>  in linux :)
