### ISSUE TITLE
PCLVisualizer crashes under Windows

### ISSUE THREAD

**Issue by TopSteely** [sergeytulyakov/FaceCept3D#4]
Hey Sergey,
using the Minimalist Pipeline the program crashes when adding the point cloud to PCLVisualizer. m_visualizer.addPointCloud(cloudObject->cloud, m_key);
Using the CloudViewer and showCloud works though. Any idea?

**Comment by M1234Thomas** [comment]
hey.. I am also facing the same issue. 
how did you manage to fix this error?
